version: "3"

services:
  postgres:
    image: postgres
    container_name: product_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=product
      - POSTGRES_DB=product
    volumes:
      - pgdata:/data/postgres
  # goapp:
  #   build: .
  #   container_name: goapp
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - product_database
  #   depends_on:
  #     - product_database

volumes:
  pgdata:
    driver: local
