// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                float32  `protobuf:"fixed32,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Total                float32  `protobuf:"fixed32,5,opt,name=Total,proto3" json:"Total,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Product) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Product) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Product) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CreateProduct struct {
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                float32  `protobuf:"fixed32,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProduct) Reset()         { *m = CreateProduct{} }
func (m *CreateProduct) String() string { return proto.CompactTextString(m) }
func (*CreateProduct) ProtoMessage()    {}
func (*CreateProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *CreateProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProduct.Unmarshal(m, b)
}
func (m *CreateProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProduct.Marshal(b, m, deterministic)
}
func (m *CreateProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProduct.Merge(m, src)
}
func (m *CreateProduct) XXX_Size() int {
	return xxx_messageInfo_CreateProduct.Size(m)
}
func (m *CreateProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProduct.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProduct proto.InternalMessageInfo

func (m *CreateProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProduct) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateProduct) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Products struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Products) Reset()         { *m = Products{} }
func (m *Products) String() string { return proto.CompactTextString(m) }
func (*Products) ProtoMessage()    {}
func (*Products) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Products) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Products.Unmarshal(m, b)
}
func (m *Products) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Products.Marshal(b, m, deterministic)
}
func (m *Products) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Products.Merge(m, src)
}
func (m *Products) XXX_Size() int {
	return xxx_messageInfo_Products.Size(m)
}
func (m *Products) XXX_DiscardUnknown() {
	xxx_messageInfo_Products.DiscardUnknown(m)
}

var xxx_messageInfo_Products proto.InternalMessageInfo

func (m *Products) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type ID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*CreateProduct)(nil), "pb.CreateProduct")
	proto.RegisterType((*Products)(nil), "pb.Products")
	proto.RegisterType((*ID)(nil), "pb.ID")
	proto.RegisterType((*Void)(nil), "pb.Void")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbf, 0x6e, 0xc2, 0x30,
	0x10, 0xc6, 0x65, 0x13, 0x0c, 0x1c, 0xa5, 0x12, 0x27, 0x06, 0x0b, 0xb5, 0x55, 0xe4, 0xa5, 0x99,
	0x32, 0xc0, 0xd8, 0x89, 0x3f, 0x12, 0x62, 0x68, 0x55, 0x21, 0x60, 0xe8, 0x96, 0xd4, 0x1e, 0x90,
	0xdc, 0xda, 0x0a, 0x66, 0xe0, 0x91, 0xfa, 0x1a, 0x7d, 0xb2, 0xca, 0x71, 0x4a, 0x93, 0xaa, 0x5b,
	0xb7, 0xbb, 0xdf, 0x77, 0xf9, 0xee, 0xcb, 0xc9, 0x30, 0xb0, 0x85, 0x91, 0xa7, 0x57, 0x97, 0xda,
	0xc2, 0x38, 0x83, 0xd4, 0xe6, 0xe2, 0x83, 0x40, 0xe7, 0x39, 0x50, 0xbc, 0x06, 0x7a, 0x90, 0x9c,
	0xc4, 0x24, 0xe9, 0x6d, 0xe8, 0x41, 0x22, 0x42, 0xf4, 0x94, 0xbd, 0x29, 0x4e, 0x4b, 0x52, 0xd6,
	0x9e, 0x6d, 0xcf, 0x56, 0xf1, 0x56, 0x60, 0xbe, 0xc6, 0x11, 0xb4, 0xf7, 0x99, 0x3e, 0x29, 0x1e,
	0xc5, 0x24, 0xa1, 0x9b, 0xd0, 0x78, 0xba, 0x35, 0x2e, 0xd3, 0xbc, 0x1d, 0x68, 0xd9, 0xe0, 0x0d,
	0xf4, 0x16, 0x85, 0xca, 0x9c, 0x92, 0x33, 0xc7, 0x59, 0x69, 0xf2, 0x03, 0xbc, 0xba, 0xb3, 0xb2,
	0x52, 0x3b, 0x41, 0xbd, 0x00, 0xf1, 0x08, 0x83, 0x30, 0xfa, 0x1d, 0xf8, 0x5f, 0x01, 0xc5, 0x14,
	0xba, 0x95, 0xd1, 0x11, 0xef, 0xa1, 0x5b, 0xdd, 0xe6, 0xc8, 0x49, 0xdc, 0x4a, 0xfa, 0x93, 0x7e,
	0x6a, 0xf3, 0xb4, 0xd2, 0x37, 0x17, 0x51, 0x8c, 0x80, 0xae, 0x97, 0xbf, 0x2f, 0x25, 0x18, 0x44,
	0x7b, 0x73, 0x90, 0x93, 0x4f, 0x02, 0xc3, 0xea, 0x9b, 0x85, 0x79, 0x77, 0x85, 0xd1, 0x5a, 0x15,
	0x98, 0x00, 0x0b, 0xb9, 0x71, 0xe8, 0x4d, 0x1b, 0xff, 0x30, 0xae, 0xef, 0xc1, 0x3b, 0xe8, 0xac,
	0x94, 0x9b, 0x9f, 0xd7, 0x12, 0x99, 0xe7, 0xeb, 0x65, 0x53, 0x8f, 0x81, 0xad, 0x94, 0x9b, 0x69,
	0x8d, 0x5d, 0x8f, 0xfd, 0xce, 0xf1, 0x55, 0x6d, 0xe0, 0x88, 0xb7, 0xc0, 0x96, 0x4a, 0x2b, 0xa7,
	0xfe, 0x36, 0x10, 0xc0, 0x76, 0xd6, 0xf9, 0x28, 0x75, 0xdc, 0x98, 0x99, 0xb3, 0x97, 0x28, 0x7d,
	0xb0, 0x79, 0xce, 0xca, 0x57, 0x32, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xbb, 0x0e, 0x0e,
	0x36, 0x02, 0x00, 0x00,
}
