name: Continuous Integration Testing

on:
  pull_request:
    branches:
      - "production"
  push:
    branches:
      - "production"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v2

      - name: Test with go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -mod=readonly -v ./...
